# Generated by Django 5.2.17 on 2026-08-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('ntn', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Information Pending', 'Information Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
