# Generated by Django 5.2.17 on 2026-09-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('Identity', 'Identity document'), ('Tax', 'Tax document'), ('Financial', 'Financial document'), ('Legal', 'Legal document'), ('Other', 'Other')], default='Other', max_length=20)),
                ('file', models.FileField(upload_to='client_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('Income Tax', 'Income Tax'), ('Sales Tax', 'Sales Tax')], max_length=20)),
                ('tax_year', models.CharField(help_text='For example: 2025-2026', max_length=9)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Information Pending', 'Information Pending'), ('In Review', 'In Review'), ('Filed', 'Filed'), ('Completed', 'Completed')], default='Draft', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='dashboard.client')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
