# Generated by Django 5.2.17 on 2026-09-05 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_seed_default_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='missing_or_corrected_request',
            field=models.TextField(blank=True, verbose_name='Missing or corrected document request'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_client_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text='Visible to the client.'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(help_text='PDF, JPG, PNG, DOC or DOCX; maximum 10 MB.', upload_to='client_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.CreateModel(
            name='TaxCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('NTN Registration', 'NTN Registration'), ('Income Tax', 'Income Tax'), ('Sales Tax', 'Sales Tax'), ('Return Filing', 'Return Filing')], max_length=30)),
                ('status', models.CharField(choices=[('Newly Registered', 'Newly Registered'), ('Under Review', 'Under Review'), ('Information Pending', 'Information Pending'), ('Processing Started', 'Processing Started'), ('Filing in Progress', 'Filing in Progress'), ('Completed', 'Completed')], default='Newly Registered', max_length=25)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target completion date')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Case notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tax_cases', to=settings.AUTH_USER_MODEL, verbose_name='Staff / tax adviser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_cases', to='dashboard.client')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.taxcase')),
            ],
            options={
                'ordering': ['is_complete', 'due_date', 'created_at'],
            },
        ),
    ]
