# Generated by Django 5.2.17 on 2026-09-05 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_clientdocument_missing_or_corrected_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='dashboard.client'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tax_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='dashboard.taxcase'),
        ),
    ]
