# Generated by Django 5.2.17 on 2026-09-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending approval'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_documents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_tax_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('STAFF', 'Staff'), ('ADMIN', 'Administrator')], default='CLIENT', max_length=10),
        ),
    ]
